update indetation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,121 +12,121 @@ jobs:
     name: Deploy on machine
     runs-on: ubuntu-latest
 
-  steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    - name: Setup node
-      uses: actions/setup-node@v4
-      with:
-        node-version: '22'
-        cache: npm
-    - name: Install dependency
-      run: npm ci
-    - name: Build application
-      run: npm run build
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: '22'
+          cache: npm
+      - name: Install dependency
+        run: npm ci
+      - name: Build application
+        run: npm run build
 
-    - name: Prepare SSH
-      env:
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_SSH: ${{ secrets.EC2_SSH }}
-      run: |
-        set -euo pipefail
-        mkdir -p ~/.ssh
-        echo "$EC2_SSH" > ~/.ssh/incident.pem
-        chmod 400 ~/.ssh/incident.pem
-        ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
+      - name: Prepare SSH
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_SSH: ${{ secrets.EC2_SSH }}
+        run: |
+          set -euo pipefail
+          mkdir -p ~/.ssh
+          echo "$EC2_SSH" > ~/.ssh/incident.pem
+          chmod 400 ~/.ssh/incident.pem
+          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
 
-    - name: Bootstrap EC2
-      env:
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
-        APP_DIR: ${{ secrets.APP_DIR }}
-      run: |
-        set -euo pipefail
-        "APP_DIR"="${APP_DIR:-/opt/incident-center}" 
-        ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
-        "bash -s -- '$APP_DIR'"  < scripts/ec2-bootstrap.sh
+      - name: Bootstrap EC2
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_USER: ${{ secrets.EC2_USER }}
+          APP_DIR: ${{ secrets.APP_DIR }}
+        run: |
+          set -euo pipefail
+          "APP_DIR"="${APP_DIR:-/opt/incident-center}" 
+          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
+          "bash -s -- '$APP_DIR'"  < scripts/ec2-bootstrap.sh
 
-    - name: Push full source to ec2
-      env:
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
-        APP_DIR: ${{ secrets.APP_DIR }}
+      - name: Push full source to ec2
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_USER: ${{ secrets.EC2_USER }}
+          APP_DIR: ${{ secrets.APP_DIR }}
 
-      run: |
-        set -euo pipefail
-        rsync -az --delete \
-        --exclude '.git' \
-        --exclude ".github" \
-        --exclude "node_modules" \
-        --exclude ".env" \
-        --exclude ".env.local" \
-        --exclude ".DS_Store" \
-        -e "ssh -i ~/.ssh/incident.pem" \
-        ./ "$EC2_USER@$EC2_HOST:$APP_DIR/"
+        run: |
+          set -euo pipefail
+          rsync -az --delete \
+          --exclude '.git' \
+          --exclude ".github" \
+          --exclude "node_modules" \
+          --exclude ".env" \
+          --exclude ".env.local" \
+          --exclude ".DS_Store" \
+          -e "ssh -i ~/.ssh/incident.pem" \
+          ./ "$EC2_USER@$EC2_HOST:$APP_DIR/"
 
-    - name: Creating env file
-      env:
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
-        APP_DIR: ${{ secrets.APP_DIR }}
-        APP_ENV: ${{ secrets.APP_ENV }}
-        WEB_ENV: ${{ secrets.WEB_ENV }}
-      run: |
-        ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
+      - name: Creating env file
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_USER: ${{ secrets.EC2_USER }}
+          APP_DIR: ${{ secrets.APP_DIR }}
+          APP_ENV: ${{ secrets.APP_ENV }}
+          WEB_ENV: ${{ secrets.WEB_ENV }}
+        run: |
+          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
 
-        cat > "$APP_DIR/apps/api/.env" << 'ENV_API'
-        $APP_ENV
-        ENV_API
+          cat > "$APP_DIR/apps/api/.env" << 'ENV_API'
+          $APP_ENV
+          ENV_API
 
-        cat > "$APP_DIR/apps/web/.env" << 'ENV_WEB'
-        $WEB_ENV
-        ENV_WEB
+          cat > "$APP_DIR/apps/web/.env" << 'ENV_WEB'
+          $WEB_ENV
+          ENV_WEB
 
-        EOF
+          EOF
 
-    - name: Verify EC2 setup
-      env:
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
-        APP_DIR: ${{ secrets.APP_DIR }}
-      run: |
-        ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
+      - name: Verify EC2 setup
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_USER: ${{ secrets.EC2_USER }}
+          APP_DIR: ${{ secrets.APP_DIR }}
+        run: |
+          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
 
-        echo "Checking dir"
+          echo "Checking dir"
 
-        test -d "$APP_DIR" || {
+          test -d "$APP_DIR" || {
 
-          echo "❌ App directory missing: $APP_DIR"
-          exit 1
+            echo "❌ App directory missing: $APP_DIR"
+            exit 1
 
-        }
+          }
 
-        test -d "$APP_DIR/apps/api/.env" || {
-          echo "❌ API directory missing"
-          exit 1
-        }
+          test -d "$APP_DIR/apps/api/.env" || {
+            echo "❌ API directory missing"
+            exit 1
+          }
 
-        test -d "$APP_DIR/apps/web/.env" || {
-          echo "❌ Web directory missing"
-          exit 1
-        }
+          test -d "$APP_DIR/apps/web/.env" || {
+            echo "❌ Web directory missing"
+            exit 1
+          }
 
-        echo "✅ EC2 verification successful"
+          echo "✅ EC2 verification successful"
 
-        EOF
+          EOF
 
-    - name: Deploy application
-      env:
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
-        APP_DIR: ${{ secrets.APP_DIR }}
+      - name: Deploy application
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_USER: ${{ secrets.EC2_USER }}
+          APP_DIR: ${{ secrets.APP_DIR }}
 
-      run: |
-        set -euo pipefail
-        APP_DIR="${APP_DIR:-/opt/incident-center}"
-        ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
-        "bash -s -- '$APP_DIR'" < scripts/ec2-deploy.sh
+        run: |
+          set -euo pipefail
+          APP_DIR="${APP_DIR:-/opt/incident-center}"
+          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
+          "bash -s -- '$APP_DIR'" < scripts/ec2-deploy.sh
 
-    - name: Deployment complete
-      run: echo "Deployment successfull."
+      - name: Deployment complete
+        run: echo "Deployment successfull."
