update yml to deploy on render

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,109 +25,114 @@ jobs:
       - name: Build application
         run: npm run build
 
-      - name: Prepare SSH
-        env:
-          EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_SSH: ${{ secrets.EC2_SSH }}
+      # - name: Prepare SSH
+      #   env:
+      #     EC2_HOST: ${{ secrets.EC2_HOST }}
+      #     EC2_SSH: ${{ secrets.EC2_SSH }}
+      #   run: |
+      #     set -euo pipefail
+      #     mkdir -p ~/.ssh
+      #     echo "$EC2_SSH" > ~/.ssh/incident.pem
+      #     chmod 400 ~/.ssh/incident.pem
+      #     ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
+
+      # - name: Bootstrap EC2
+      #   env:
+      #     EC2_HOST: ${{ secrets.EC2_HOST }}
+      #     EC2_USER: ${{ secrets.EC2_USER }}
+      #     APP_DIR: ${{ secrets.APP_DIR }}
+      #   run: |
+      #     set -euo pipefail
+      #     APP_DIR="${APP_DIR:-/opt/incident-center}"
+      #     ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
+      #     "bash -s -- '$APP_DIR'"  < scripts/ec2-bootstrap.sh
+
+      # - name: Push full source to ec2
+      #   env:
+      #     EC2_HOST: ${{ secrets.EC2_HOST }}
+      #     EC2_USER: ${{ secrets.EC2_USER }}
+      #     APP_DIR: ${{ secrets.APP_DIR }}
+
+      #   run: |
+      #     set -euo pipefail
+      #     APP_DIR="${APP_DIR:-/opt/incident-center}"
+      #     rsync -az --delete \
+      #     --exclude '.git' \
+      #     --exclude ".github" \
+      #     --exclude "node_modules" \
+      #     --exclude ".env" \
+      #     --exclude ".env.local" \
+      #     --exclude ".DS_Store" \
+      #     -e "ssh -i ~/.ssh/incident.pem" \
+      #     ./ "$EC2_USER@$EC2_HOST:$APP_DIR/"
+
+      # - name: Creating env file
+      #   env:
+      #     EC2_HOST: ${{ secrets.EC2_HOST }}
+      #     EC2_USER: ${{ secrets.EC2_USER }}
+      #     APP_DIR: ${{ secrets.APP_DIR }}
+      #     APP_ENV: ${{ secrets.APP_ENV }}
+      #     WEB_ENV: ${{ secrets.WEB_ENV }}
+      #   run: |
+      #     ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
+
+      #     cat > "$APP_DIR/apps/api/.env" << 'ENV_API'
+      #     $APP_ENV
+      #     ENV_API
+
+      #     cat > "$APP_DIR/apps/web/.env" << 'ENV_WEB'
+      #     $WEB_ENV
+      #     ENV_WEB
+
+      #     EOF
+
+      # - name: Verify EC2 setup
+      #   env:
+      #     EC2_HOST: ${{ secrets.EC2_HOST }}
+      #     EC2_USER: ${{ secrets.EC2_USER }}
+      #     APP_DIR: ${{ secrets.APP_DIR }}
+      #   run: |
+      #     ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
+
+      #     echo "Checking dir"
+
+      #     test -d "$APP_DIR" || {
+
+      #       echo "❌ App directory missing: $APP_DIR"
+      #       exit 1
+
+      #     }
+
+      #     test -f "$APP_DIR/apps/api/.env" || {
+      #       echo "❌ API directory missing"
+      #       exit 1
+      #     }
+
+      #     test -f "$APP_DIR/apps/web/.env" || {
+      #       echo "❌ Web directory missing"
+      #       exit 1
+      #     }
+
+      #     echo "✅ EC2 verification successful"
+
+      #     EOF
+
+      # - name: Deploy application
+      #   env:
+      #     EC2_HOST: ${{ secrets.EC2_HOST }}
+      #     EC2_USER: ${{ secrets.EC2_USER }}
+      #     APP_DIR: ${{ secrets.APP_DIR }}
+
+      #   run: |
+      #     set -euo pipefail
+      #     APP_DIR="${APP_DIR:-/opt/incident-center}"
+      #     ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
+      #     "bash -s -- '$APP_DIR'" < scripts/ec2-deploy.sh
+      - name: Deploy backend on render
         run: |
-          set -euo pipefail
-          mkdir -p ~/.ssh
-          echo "$EC2_SSH" > ~/.ssh/incident.pem
-          chmod 400 ~/.ssh/incident.pem
-          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
-
-      - name: Bootstrap EC2
-        env:
-          EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_USER: ${{ secrets.EC2_USER }}
-          APP_DIR: ${{ secrets.APP_DIR }}
+          curl -X POST ${{ secrets.RENDER_DEPLOY_API_HOOK  }}
+      - name: Deploy web on render
         run: |
-          set -euo pipefail
-          APP_DIR="${APP_DIR:-/opt/incident-center}" 
-          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
-          "bash -s -- '$APP_DIR'"  < scripts/ec2-bootstrap.sh
-
-      - name: Push full source to ec2
-        env:
-          EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_USER: ${{ secrets.EC2_USER }}
-          APP_DIR: ${{ secrets.APP_DIR }}
-
-        run: |
-          set -euo pipefail
-          APP_DIR="${APP_DIR:-/opt/incident-center}"
-          rsync -az --delete \
-          --exclude '.git' \
-          --exclude ".github" \
-          --exclude "node_modules" \
-          --exclude ".env" \
-          --exclude ".env.local" \
-          --exclude ".DS_Store" \
-          -e "ssh -i ~/.ssh/incident.pem" \
-          ./ "$EC2_USER@$EC2_HOST:$APP_DIR/"
-
-      - name: Creating env file
-        env:
-          EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_USER: ${{ secrets.EC2_USER }}
-          APP_DIR: ${{ secrets.APP_DIR }}
-          APP_ENV: ${{ secrets.APP_ENV }}
-          WEB_ENV: ${{ secrets.WEB_ENV }}
-        run: |
-          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
-
-          cat > "$APP_DIR/apps/api/.env" << 'ENV_API'
-          $APP_ENV
-          ENV_API
-
-          cat > "$APP_DIR/apps/web/.env" << 'ENV_WEB'
-          $WEB_ENV
-          ENV_WEB
-
-          EOF
-
-      - name: Verify EC2 setup
-        env:
-          EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_USER: ${{ secrets.EC2_USER }}
-          APP_DIR: ${{ secrets.APP_DIR }}
-        run: |
-          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" << EOF
-
-          echo "Checking dir"
-
-          test -d "$APP_DIR" || {
-
-            echo "❌ App directory missing: $APP_DIR"
-            exit 1
-
-          }
-
-          test -f "$APP_DIR/apps/api/.env" || {
-            echo "❌ API directory missing"
-            exit 1
-          }
-
-          test -f "$APP_DIR/apps/web/.env" || {
-            echo "❌ Web directory missing"
-            exit 1
-          }
-
-          echo "✅ EC2 verification successful"
-
-          EOF
-
-      - name: Deploy application
-        env:
-          EC2_HOST: ${{ secrets.EC2_HOST }}
-          EC2_USER: ${{ secrets.EC2_USER }}
-          APP_DIR: ${{ secrets.APP_DIR }}
-
-        run: |
-          set -euo pipefail
-          APP_DIR="${APP_DIR:-/opt/incident-center}"
-          ssh -i ~/.ssh/incident.pem "$EC2_USER@$EC2_HOST" \
-          "bash -s -- '$APP_DIR'" < scripts/ec2-deploy.sh
-
+          curl -X POST ${{ secrets.RENDER_DEPLOY_WEB_HOOK  }}
       - name: Deployment complete
         run: echo "Deployment successfull."
